version: "3.8"

services:
  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: meditrack
      POSTGRES_PASSWORD: meditrack123
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data
    networks:
      - meditrack-network

  postgres-appointment:
    image: postgres:15
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: meditrack
      POSTGRES_PASSWORD: meditrack123
    ports:
      - "5433:5432"
    volumes:
      - appointment-data:/var/lib/postgresql/data
    networks:
      - meditrack-network

  postgres-ehr:
    image: postgres:15
    environment:
      POSTGRES_DB: ehr_db
      POSTGRES_USER: meditrack
      POSTGRES_PASSWORD: meditrack123
    ports:
      - "5434:5432"
    volumes:
      - ehr-data:/var/lib/postgresql/data
    networks:
      - meditrack-network

  postgres-pharmacy:
    image: postgres:15
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: meditrack
      POSTGRES_PASSWORD: meditrack123
    ports:
      - "5435:5432"
    volumes:
      - pharmacy-data:/var/lib/postgresql/data
    networks:
      - meditrack-network

  postgres-analytics:
    image: postgres:15
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: meditrack
      POSTGRES_PASSWORD: meditrack123
    ports:
      - "5436:5432"
    volumes:
      - analytics-data:/var/lib/postgresql/data
    networks:
      - meditrack-network

  postgres-payment:
    image: postgres:15
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: meditrack
      POSTGRES_PASSWORD: meditrack123
    ports:
      - "5437:5432"
    volumes:
      - payment-data:/var/lib/postgresql/data
    networks:
      - meditrack-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - meditrack-network

  eureka-server:
    image: meditrack/eureka-server:latest
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - meditrack-network

networks:
  meditrack-network:
    driver: bridge

volumes:
  auth-data:
  appointment-data:
  ehr-data:
  pharmacy-data:
  analytics-data:
  payment-data:
